name: sre-lab-localstack

services:
  localstack:
    image: localstack/localstack:latest@sha256:4abc29e923e5ed8a63d6c705a9dfa74b15d560e7055845299d87b22dabf9f6e2
    container_name: sre-lab-localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN:?defina LOCALSTACK_AUTH_TOKEN no .env}
      SERVICES: s3,sqs,secretsmanager,iam,sts
      PERSISTENCE: "0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 12
